apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-with-secrets
  name: deployment-with-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-with-secrets
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-with-secrets
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: alpine
        name: alpine
        resources: {}
status: {}
